### ISSUE TITLE
Feature Request: Movable Anchor

### ISSUE THREAD

**Issue by neonvoidx** [jobackman/SpellNotifications#3]
Would love to see an anchor for this that lets you move around where the text will display at, instead of locked at top mid of screen

**Comment by jobackman** [comment]
As it was written by Veev the addon re-uses blizzard's standard ui elements  `ZoneTextString` and `UIErrorsFrame` for printing the big and small text. If I were to move either anchor it would also mean that it would also move quest objective updates and the _you entered this zone_ announcement: 
![image](https://user-images.githubusercontent.com/732505/114569816-96cc2500-9c75-11eb-9cf6-1066e724f217.png)

I dont think that is something this addon should alter to be honest. 

If we were to add these option it would require some new elements be made for this to separate it from the default ones as well as options added to the addon. I haven't planned to refactor any of this, though I am definitely open to accepting contributions if someone wants to take this on 👍 

Personally I like it being defaulted to the wow placements, but if you really want this option to move it regardless of the caveats I bet that [MoveAnything][1] can move the two frames:  `ZoneTextString` and `UIErrorsFrame` 

[1]: https://www.curseforge.com/wow/addons/move-anything
